name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  github-token:
    description: 'GitHub token to push Docker image to GitHub Packages'
    required: true
  image-name:
    description: 'Docker Image name'
    required: true
  image-tag:
    description: 'Docker Image tag'
    default: "latest"
    required: false
  extract-git-tag:
    description: 'Extract git-tag from repository'
    default: "false"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.github-token }}
    - ${{ inputs.image-name }}
    - ${{ inputs.image-tag }}
    - ${{ inputs.extract-git-tag }}
branding:
  icon: 'box'
  color: 'blue'
outputs:
  time: # id of output
    description: 'The time we greeted you'
